// Registry of APNs broadcast channel IDs — one channel per APNs environment.
//
// A channel is the addressable thing a fleet Live Activity subscribes to. Unlike
// the per-card `activityUpdate` token it replaces, a channel is a property of the
// APP, not of any one card: it outlives every card, needs no background wake to
// obtain, and reaches every subscribed card at once. That is the whole point —
// see `.claude/feature/live-activity-broadcast-channel.md`.
//
// Keyed by env because Apple is explicit that "a channel created in the
// development environment can't be used in the production environment".
import { dirname, join } from "node:path";
import { mkdir } from "node:fs/promises";
import { PATHS } from "../config.ts";

export type ApnsEnv = "sandbox" | "production";

export type LiveActivityChannel = {
  env: ApnsEnv;
  /// Base64, generated by APNs. Apple: "don't make assumptions on the channel ID size."
  channelId: string;
  createdAt: number;
};

const storePath = () =>
  process.env.LFG_LIVE_ACTIVITY_CHANNEL_STORE ??
  join(PATHS.data, "live-activity-channels.json");

function usable(row: unknown): row is LiveActivityChannel {
  const r = row as Partial<LiveActivityChannel> | null;
  return !!r && (r.env === "sandbox" || r.env === "production") && !!r.channelId;
}

export async function listLiveActivityChannels(): Promise<LiveActivityChannel[]> {
  const f = Bun.file(storePath());
  if (!(await f.exists())) return [];
  try {
    const parsed = JSON.parse(await f.text()) as unknown;
    if (!Array.isArray(parsed)) return [];
    // Rows without a usable id are dropped on read, not just on write: a file
    // hand-edited or written by an older build must never hand out a channel id
    // that APNs will reject — a card started against an invalid channel does not
    // start at all.
    return parsed.filter(usable);
  } catch {
    // A corrupt file is equivalent to having no channel: the caller creates one.
    return [];
  }
}

async function write(list: LiveActivityChannel[]): Promise<void> {
  await mkdir(dirname(storePath()), { recursive: true });
  await Bun.write(storePath(), JSON.stringify(list, null, 2));
}

export async function getLiveActivityChannel(env: ApnsEnv): Promise<LiveActivityChannel | null> {
  return (await listLiveActivityChannels()).find((c) => c.env === env) ?? null;
}

/**
 * Record the channel for an environment, replacing any previous one.
 *
 * Replacement rather than append is deliberate: two rows for one env would make
 * "which channel is the live card listening on?" unanswerable, and every card
 * already on a device is subscribed to exactly one channel id chosen at start.
 */
export async function saveLiveActivityChannel(
  env: ApnsEnv,
  channelId: string,
): Promise<LiveActivityChannel> {
  const record: LiveActivityChannel = { env, channelId, createdAt: Date.now() };
  const rest = (await listLiveActivityChannels()).filter((c) => c.env !== env);
  await write([...rest, record]);
  return record;
}

export async function removeLiveActivityChannel(env: ApnsEnv): Promise<void> {
  const list = await listLiveActivityChannels();
  const next = list.filter((c) => c.env !== env);
  if (next.length !== list.length) await write(next);
}
